project:
  type: website
  output-dir: docs
  
website:
  title: "Manuel Rojas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - CV.qmd  
      - Research.qmd
      - Teaching.qmd

format:
  html:
    theme: 
      light: Flatly
      dark: Darkly
    css: styles.css
    page-layout: full
    
editor: visual

