project:
  type: website
  output-dir: docs
  
website:
  title: "Manuel Felipe Rojas Echeverri"
  navbar:
    left:
      - text: "Research"
        href: Research/Research.qmd
      - text: "CV"
        href: CV/CV.qmd
      - text: "Teaching"
        href: Teaching/Teaching.qmd

google-analytics: G-VQ1QYPQYP8

format:
  html:
    theme: 
      light: Flatly
      dark: Darkly
    css: styles.css
    page-layout: full
    
editor: visual

