project:
  type: website
  output-dir: docs
  
website:
  google-analytics: "G-VQ1QYPQYP8"
  title: "Manuel Felipe Rojas Echeverri"
  navbar:
    left:
      - text: "Research"
        href: Research/Research.qmd
      - text: "CV"
        href: CV/CV.qmd
      - text: "Teaching"
        href: Teaching/Teaching.qmd
body-footer: |
    <!-- 100% privacy-first analytics -->
    <script async defer src="https://scripts.simpleanalyticscdn.com/latest.js"></script>
    <noscript><img src="https://queue.simpleanalyticscdn.com/noscript.gif" alt="" referrerpolicy="no-referrer-when-downgrade" /></noscript>

format:
  html:
    theme: 
      light: Flatly
      dark: Darkly
    css: styles.css
    page-layout: full
    
editor: visual

