---
title: "Research"
---

### Distributional Effects of a Non-Linear Price Scheme in Water Utilities:

In this paper, I study a non-linear price scheme on a necessity good and its implications, focusing on a case of study from a developing country. Specifically, this paper has two objectives: to provide reliable price and income elasticities for a necessity good (i.e., water consumption) when it has a non-linear price scheme and to evaluate the distributional effects of this kind of price scheme. The case of study is the city of Bogotá, Colombia. Bogotá presents a particularity: not all households face the same pricing scheme for water utilities. Some households face a linear price scheme, and others a non-linear one. In addition to this, in 2012, the city's government introduced a policy that added more non-linearities to the price scheme for some specific groups of households. In order to study these types of price schemes and their implications, I built a novel data set merging the billing information of the households obtained from administrative data with the households' socioeconomic characteristics obtained from survey data, accounting for periods before and after the introduction of the policy in 2012. I propose a reduce form analysis using a Changes in Changes model to evaluate the effects of this policy and, once I control by variables that proxy the households' income, I find that the effects of the policy on water consumption are null. I then propose a structural model for water demand to rationalize the results from the reduced form and estimate the price elasticities and income elasticities of water consumption.

In contrast to the previous literature, the price elasticities I estimate in this paper are small, and the income elasticities are significant. With the structural model, I also conduct counterfactual exercises, changing the price schemes of the households to estimate the impact on the distribution of welfare of a non-linear price scheme. I conclude by proposing alternative price schemes that prove to improve the households' welfare.
