---
title: Research
---

# Working Papers

### Distributional Effects of a Non-Linear Price Scheme in Public Utilities. (Job Market Paper)

[Latest Version](https://github.com/Mazathoth1/manuelrojas.github.io/raw/5236afa3433a43a4d4bd14b927ab62f390f406ef/Research/Distributional_Effects_Manuel_Rojas.pdf)

Nonlinear pricing schemes are the primary instruments that policymakers use to ensure access to public utilities for low-income households while penalizing high-income households for overconsumption. In this paper, I evaluate the effectiveness of these pricing schemes and introduce a novel methodology to analyze their impact on the distribution of consumption and welfare in public utilities, with a specific focus on the case of water utilities in Bogotá, Colombia. To achieve this, I employ a combination of reduced-form and structural model techniques, leveraging Bogotá's unique context, where households have historically encountered diverse pricing schemes, including the introduction of additional nonlinear elements in the pricing scheme through a 2012 policy change. Notably, the results reveal that the nonlinear pricing scheme exhibits regressive characteristics, benefiting wealthier households with higher consumption levels and more significant welfare gains. Furthermore, the evidence suggests that income effects, driven by changes in the virtual incomes of households, are the primary driving force behind these outcomes. These findings underscore the necessity for an alternative approach to achieving more significant equity in the distribution of benefits within public utilities.

### The Water Vital Minimum: Analyzing the Bogotá Free Water Policy.

[Latest Version](https://github.com/Mazathoth1/manuelrojas.github.io/raw/819647da1ac8fa8f38e8a7f62bf96ecbb5a307bc/Research/Vital_Minimum.pdf)

With: Juan Miguel Gallego, Juan Daniel Oviedo and Carlos Sepulveda.

Szabo (2015) analyzes the effects of a free water allowance in South Africa equal to the World Health Organization's recommended minimum. The author demonstrates that the free allowance acts as a lump-sum subsidy without significantly affecting water consumption. Furthermore, it is shown that it is possible to reallocate the current subsidy to form an optimal tariff without needing a free allowance. In this study, we revisit Szabo's analysis using data from Bogotá, Colombia, where a similar policy was implemented. First, employing the methodology proposed by the author, we successfully replicate the original results on consumption, revealing a minimal impact. Second, we reexamine the calculation of the price elasticities for water, identifying lower price elasticities. Third, we replicate the exercise of creating an optimal tariff that increases social welfare.

# Work in Progress

### Empowering Women Caregivers Entrepreneurs in Bogotá, Colombia

With: Yuliet Verbel, Hernando Zuleta, and María del Pilar López-Uribe

### Race Against the Machines? AI-Augmented Job Training Support for Women and Older Workers in Bogotá.

With: Cristina Butnaru, Christopher Neilson, Andrea Otero, Christian Posso, Hernando Zuleta., and María del Pilar López-Uribe

### Social Norms and Caregiving Women: An Educational Intervention to Promote a More Equitable Distribution of Carework

With: Veronica Abril, Amalia Rodriguez, and Yuliet Verbel

### Bundling and Market Power in Telecommunication Markets

# Peer-Reviewed Publications in Spanish

### Los efectos de la productividad sobre la participación en grupos de capital social: un estudio para firmas pequeñas e informales en Colombia

[Revista de Economía del Rosario 27(1), 1–34](https://revistas.urosario.edu.co/index.php/economia/article/view/14916)
